//! Persistent P-256 identity generated by rcgen/ring. Never log secret material.
use crate::{DeviceId, Error, Result};
use rcgen::{CertificateParams, KeyPair, PublicKeyData};
use rustls::pki_types::{CertificateDer, PrivateKeyDer, PrivatePkcs8KeyDer};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    fs::{self, OpenOptions},
    io::{Read, Write},
    path::Path,
};

const MAX_IDENTITY_BYTES: u64 = 16 * 1024;

#[derive(Serialize, Deserialize)]
struct DiskIdentity {
    version: u16,
    key: Vec<u8>,
    certificate: Vec<u8>,
}

/// An identity is deliberately not `Debug` or `Serialize` to avoid leaking keys.
pub struct Identity {
    key: Vec<u8>,
    certificate: Vec<u8>,
    id: DeviceId,
}

impl Identity {
    pub fn load_or_create(directory: &Path) -> Result<Self> {
        fs::create_dir_all(directory)?;
        let path = directory.join("identity.bin");
        if path.exists() {
            return Self::load(&path);
        }
        let key = KeyPair::generate()?;
        let certificate = CertificateParams::new(vec!["zenith.local".into()])?.self_signed(&key)?;
        let disk = DiskIdentity {
            version: 1,
            key: key.serialize_der(),
            certificate: certificate.der().to_vec(),
        };
        let bytes = postcard::to_allocvec(&disk)?;
        // A single create_new file prevents mixing keys and certs or overwriting
        // another process's identity. A crash during first write fails closed.
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        match options.open(&path) {
            Ok(mut file) => {
                file.write_all(&bytes)?;
                file.sync_all()?;
            }
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => return Self::load(&path),
            Err(e) => return Err(e.into()),
        }
        Self::from_disk(disk)
    }
    fn load(path: &Path) -> Result<Self> {
        let file = fs::File::open(path)?;
        if file.metadata()?.len() > MAX_IDENTITY_BYTES {
            return Err(Error::Invalid("identity size"));
        }
        let mut bytes = Vec::new();
        file.take(MAX_IDENTITY_BYTES + 1).read_to_end(&mut bytes)?;
        let (disk, tail) = postcard::take_from_bytes(&bytes)?;
        if !tail.is_empty() {
            return Err(Error::Invalid("identity trailing bytes"));
        }
        Self::from_disk(disk)
    }
    fn from_disk(disk: DiskIdentity) -> Result<Self> {
        if disk.version != 1 {
            return Err(Error::Invalid("identity version"));
        }
        let key_der = PrivatePkcs8KeyDer::from(disk.key.clone());
        let key = KeyPair::from_pkcs8_der_and_sign_algo(&key_der, &rcgen::PKCS_ECDSA_P256_SHA256)?;
        let (_, cert) = x509_parser::parse_x509_certificate(&disk.certificate)
            .map_err(|_| Error::Invalid("certificate DER"))?;
        if key.subject_public_key_info() != cert.public_key().raw {
            return Err(Error::Invalid("certificate/key mismatch"));
        }
        let id = certificate_id(&disk.certificate)?;
        Ok(Self {
            key: disk.key,
            certificate: disk.certificate,
            id,
        })
    }
    pub fn id(&self) -> DeviceId {
        self.id
    }
    pub fn certificate(&self) -> CertificateDer<'static> {
        CertificateDer::from(self.certificate.clone())
    }
    /// Only pass to TLS configuration; do not persist or display this value.
    pub fn private_key(&self) -> PrivateKeyDer<'static> {
        PrivatePkcs8KeyDer::from(self.key.clone()).into()
    }
}

/// Derive the peer ID and refuse trailing DER bytes. Identity and TLS pinning are
/// separate: S04 pins the entire certificate fingerprint as well as this key ID.
pub fn certificate_id(der: &[u8]) -> Result<DeviceId> {
    let (tail, cert) =
        x509_parser::parse_x509_certificate(der).map_err(|_| Error::Invalid("certificate DER"))?;
    if !tail.is_empty() {
        return Err(Error::Invalid("certificate trailing bytes"));
    }
    Ok(DeviceId(Sha256::digest(cert.public_key().raw).into()))
}

pub fn certificate_fingerprint(der: &[u8]) -> [u8; 32] {
    Sha256::digest(der).into()
}
